import { NgFor, NgIf } from '@angular/common';
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-paginacion',
  imports: [NgFor, NgIf],
  templateUrl: './paginacion.component.html',
  styleUrl: './paginacion.component.css'
})
export class PaginacionComponent {
  @Output() eventPais = new EventEmitter<string>();
  @Input() pais1: string = 'Ecuador';

  public paises = [
    { nombre: "Afghanistan", codigo: "af" },
    { nombre: "Albania", codigo: "al" },
    { nombre: "Germany", codigo: "de" },
    { nombre: "Andorra", codigo: "ad" },
    { nombre: "Angola", codigo: "ao" },
    { nombre: "Antigua and Barbuda", codigo: "ag" },
    { nombre: "Saudi Arabia", codigo: "sa" },
    { nombre: "Algeria", codigo: "dz" },
    { nombre: "Argentina", codigo: "ar" },
    { nombre: "Armenia", codigo: "am" },
    { nombre: "Australia", codigo: "au" },
    { nombre: "Austria", codigo: "at" },
    { nombre: "Azerbaijan", codigo: "az" },
    { nombre: "Bahamas", codigo: "bs" },
    { nombre: "Bangladesh", codigo: "bd" },
    { nombre: "Barbados", codigo: "bb" },
    { nombre: "Bahrain", codigo: "bh" },
    { nombre: "Belgium", codigo: "be" },
    { nombre: "Belize", codigo: "bz" },
    { nombre: "Benin", codigo: "bj" },
    { nombre: "Belarus", codigo: "by" },
    { nombre: "Myanmar", codigo: "mm" },
    { nombre: "Bolivia", codigo: "bo" },
    { nombre: "Bosnia and Herzegovina", codigo: "ba" },
    { nombre: "Botswana", codigo: "bw" },
    { nombre: "Brazil", codigo: "br" },
    { nombre: "Brunei", codigo: "bn" },
    { nombre: "Bulgaria", codigo: "bg" },
    { nombre: "Burkina Faso", codigo: "bf" },
    { nombre: "Burundi", codigo: "bi" },
    { nombre: "Bhutan", codigo: "bt" },
    { nombre: "Cape Verde", codigo: "cv" },
    { nombre: "Cambodia", codigo: "kh" },
    { nombre: "Cameroon", codigo: "cm" },
    { nombre: "Canada", codigo: "ca" },
    { nombre: "Qatar", codigo: "qa" },
    { nombre: "Chad", codigo: "td" },
    { nombre: "Chile", codigo: "cl" },
    { nombre: "China", codigo: "cn" },
    { nombre: "Cyprus", codigo: "cy" },
    { nombre: "Colombia", codigo: "co" },
    { nombre: "Comoros", codigo: "km" },
    { nombre: "North Korea", codigo: "kp" },
    { nombre: "South Korea", codigo: "kr" },
    { nombre: "Ivory Coast", codigo: "ci" },
    { nombre: "Costa Rica", codigo: "cr" },
    { nombre: "Croatia", codigo: "hr" },
    { nombre: "Cuba", codigo: "cu" },
    { nombre: "Denmark", codigo: "dk" },
    { nombre: "Dominica", codigo: "dm" },
    { nombre: "Ecuador", codigo: "ec" },
    { nombre: "Egypt", codigo: "eg" },
    { nombre: "El Salvador", codigo: "sv" },
    { nombre: "United Arab Emirates", codigo: "ae" },
    { nombre: "Eritrea", codigo: "er" },
    { nombre: "Slovakia", codigo: "sk" },
    { nombre: "Slovenia", codigo: "si" },
    { nombre: "Spain", codigo: "es" },
    { nombre: "United States", codigo: "us" },
    { nombre: "Estonia", codigo: "ee" },
    { nombre: "Eswatini", codigo: "sz" },
    { nombre: "Ethiopia", codigo: "et" },
    { nombre: "Philippines", codigo: "ph" },
    { nombre: "Finland", codigo: "fi" },
    { nombre: "Fiji", codigo: "fj" },
    { nombre: "France", codigo: "fr" },
    { nombre: "Gabon", codigo: "ga" },
    { nombre: "Gambia", codigo: "gm" },
    { nombre: "Georgia", codigo: "ge" },
    { nombre: "Ghana", codigo: "gh" },
    { nombre: "Grenada", codigo: "gd" },
    { nombre: "Greece", codigo: "gr" },
    { nombre: "Guatemala", codigo: "gt" },
    { nombre: "Guinea", codigo: "gn" },
    { nombre: "Equatorial Guinea", codigo: "gq" },
    { nombre: "Guinea-Bissau", codigo: "gw" },
    { nombre: "Guyana", codigo: "gy" },
    { nombre: "Haiti", codigo: "ht" },
    { nombre: "Honduras", codigo: "hn" },
    { nombre: "Hungary", codigo: "hu" },
    { nombre: "India", codigo: "in" },
    { nombre: "Indonesia", codigo: "id" },
    { nombre: "Iraq", codigo: "iq" },
    { nombre: "Iran", codigo: "ir" },
    { nombre: "Ireland", codigo: "ie" },
    { nombre: "Iceland", codigo: "is" },
    { nombre: "Marshall Islands", codigo: "mh" },
    { nombre: "Solomon Islands", codigo: "sb" },
    { nombre: "Israel", codigo: "il" },
    { nombre: "Italy", codigo: "it" },
    { nombre: "Jamaica", codigo: "jm" },
    { nombre: "Japan", codigo: "jp" },
    { nombre: "Jordan", codigo: "jo" },
    { nombre: "Kazakhstan", codigo: "kz" },
    { nombre: "Kenya", codigo: "ke" },
    { nombre: "Kyrgyzstan", codigo: "kg" },
    { nombre: "Kiribati", codigo: "ki" },
    { nombre: "Kuwait", codigo: "kw" },
    { nombre: "Laos", codigo: "la" },
    { nombre: "Lesotho", codigo: "ls" },
    { nombre: "Latvia", codigo: "lv" },
    { nombre: "Lebanon", codigo: "lb" },
    { nombre: "Liberia", codigo: "lr" },
    { nombre: "Libya", codigo: "ly" },
    { nombre: "Liechtenstein", codigo: "li" },
    { nombre: "Lithuania", codigo: "lt" },
    { nombre: "Luxembourg", codigo: "lu" },
    { nombre: "North Macedonia", codigo: "mk" },
    { nombre: "Madagascar", codigo: "mg" },
    { nombre: "Malaysia", codigo: "my" },
    { nombre: "Malawi", codigo: "mw" },
    { nombre: "Maldives", codigo: "mv" },
    { nombre: "Mali", codigo: "ml" },
    { nombre: "Malta", codigo: "mt" },
    { nombre: "Morocco", codigo: "ma" },
    { nombre: "Mauritius", codigo: "mu" },
    { nombre: "Mauritania", codigo: "mr" },
    { nombre: "Mexico", codigo: "mx" },
    { nombre: "Micronesia", codigo: "fm" },
    { nombre: "Moldova", codigo: "md" },
    { nombre: "Monaco", codigo: "mc" },
    { nombre: "Mongolia", codigo: "mn" },
    { nombre: "Montenegro", codigo: "me" },
    { nombre: "Mozambique", codigo: "mz" },
    { nombre: "Namibia", codigo: "na" },
    { nombre: "Nauru", codigo: "nr" },
    { nombre: "Nepal", codigo: "np" },
    { nombre: "Nicaragua", codigo: "ni" },
    { nombre: "Niger", codigo: "ne" },
    { nombre: "Nigeria", codigo: "ng" },
    { nombre: "Norway", codigo: "no" },
    { nombre: "New Zealand", codigo: "nz" },
    { nombre: "Oman", codigo: "om" },
    { nombre: "Netherlands", codigo: "nl" },
    { nombre: "Pakistan", codigo: "pk" },
    { nombre: "Palau", codigo: "pw" },
    { nombre: "Panama", codigo: "pa" },
    { nombre: "Papua New Guinea", codigo: "pg" },
    { nombre: "Paraguay", codigo: "py" },
    { nombre: "Peru", codigo: "pe" },
    { nombre: "Poland", codigo: "pl" },
    { nombre: "Portugal", codigo: "pt" },
    { nombre: "United Kingdom", codigo: "gb" },
    { nombre: "Central African Republic", codigo: "cf" },
    { nombre: "Czech Republic", codigo: "cz" },
    { nombre: "Democratic Republic of the Congo", codigo: "cd" },
    { nombre: "Republic of the Congo", codigo: "cg" },
    { nombre: "Dominican Republic", codigo: "do" },
    { nombre: "Rwanda", codigo: "rw" },
    { nombre: "Romania", codigo: "ro" },
    { nombre: "South Africa", codigo: "za" },
    { nombre: "South Sudan", codigo: "ss" },
    { nombre: "Sri Lanka", codigo: "lk" },
    { nombre: "Sudan", codigo: "sd" },
    { nombre: "Suriname", codigo: "sr" },
    { nombre: "Sweden", codigo: "se" },
    { nombre: "Switzerland", codigo: "ch" },
    { nombre: "Syria", codigo: "sy" },
    { nombre: "Tajikistan", codigo: "tj" },
    { nombre: "Tanzania", codigo: "tz" },
    { nombre: "Thailand", codigo: "th" },
    { nombre: "Timor-Leste", codigo: "tl" },
    { nombre: "Togo", codigo: "tg" },
    { nombre: "Tonga", codigo: "to" },
    { nombre: "Trinidad and Tobago", codigo: "tt" },
    { nombre: "Tunisia", codigo: "tn" },
    { nombre: "Turkey", codigo: "tr" },
    { nombre: "Turkmenistan", codigo: "tm" },
    { nombre: "Tuvalu", codigo: "tv" },
    { nombre: "Uganda", codigo: "ug" },
    { nombre: "Ukraine", codigo: "ua" },
    { nombre: "United Arab Emirates", codigo: "ae" },
    { nombre: "United Kingdom", codigo: "gb" },
    { nombre: "United States", codigo: "us" },
    { nombre: "Uruguay", codigo: "uy" },
    { nombre: "Uzbekistan", codigo: "uz" },
    { nombre: "Vanuatu", codigo: "vu" },
    { nombre: "Vatican City", codigo: "va" },
    { nombre: "Venezuela", codigo: "ve" },
    { nombre: "Vietnam", codigo: "vn" },
    { nombre: "Yemen", codigo: "ye" },
    { nombre: "Zambia", codigo: "zm" },
    { nombre: "Zimbabwe", codigo: "zw" }
  ];


  mandarpais(pais: string) {
    this.pais1 = pais;
    this.eventPais.emit(this.pais1);
  }

}
